# baseline config
NUM_EPOCHES = 100
BATCH_SIZE = 256
LEARNING_RATE = 0.001

# feature extract
N_MFCC = 128
N_MEL = 128
NAME_FEATURES_MFCC = "mfcc"
NAME_FEATURES_MEL = "mel"
NAME_FEATURES_NPCC = "npcc"
NAME_FEATURES_PROJECT = NAME_FEATURES_MEL
NUM_N_FEATURE = N_MEL

# feature file
NAME_TRAIN_LABEL_FILE = f"train_label_{NAME_FEATURES_PROJECT}_n_{NUM_N_FEATURE}"
NAME_TRAIN_FEATURES_FILE = f"train_features_{NAME_FEATURES_PROJECT}_n_{NUM_N_FEATURE}"
NAME_TEST_LABEL_FILE = f"test_label_{NAME_FEATURES_PROJECT}_n_{NUM_N_FEATURE}"
NAME_TEST_FEATURES_FILE = f"test_features_{NAME_FEATURES_PROJECT}_n_{NUM_N_FEATURE}"

# log file
NAME_MODEL_PERFORMANCE_FILE = f"model_feature_{NAME_FEATURES_PROJECT}_epoch_{NUM_EPOCHES}_batch_{BATCH_SIZE}"
NAME_MODEL_PERFORMANCE_BEST_FILE = f"model_feature_{NAME_FEATURES_PROJECT}_epoch_{NUM_EPOCHES}_batch_{BATCH_SIZE}_best"